Hw10
subject-name-here/Java-Fall2017-202 pull request #16
Opened 2018-03-08 08:27 UTC by subject-name-here

2018-03-17 07:07 UTC, jzuken requested changes

2018-03-17 07:07 UTC, jzuken commented on hw10/src/main/java/ru/spbau/mit/java/paradov/ThreadPoolImpl.java
> +        private Object result;
это какая-то непонятная экономия. что мешало ещё одно поле для исключения завести? и тогда enum со статусом не нужен был бы. и не пришлось делать странно выглядящих unchecked cast'ов

2018-03-17 07:07 UTC, jzuken commented on hw10/src/main/java/ru/spbau/mit/java/paradov/LightExecutionException.java
> +public class LightExecutionException extends RuntimeException {
а зачем ему быть непроверяемым?

2018-03-17 12:09 UTC, subject-name-here commented on hw10/src/main/java/ru/spbau/mit/java/paradov/LightExecutionException.java
> +public class LightExecutionException extends RuntimeException {
но оно ведь появляется только из-за непроверяемых исключений
и оно тоже непроверяемое в прямом смысле слова: мы даже не можем узнать, бросил supplier исключение или нет

2018-03-18 12:49 UTC, jzuken commented on hw10/src/main/java/ru/spbau/mit/java/paradov/LightExecutionException.java
> +public class LightExecutionException extends RuntimeException {
мы можем узнать, что supplier что-то бросил, если напишем обработчик. а проверяемость LightExecutionException гарантирует нам, что клиенты нашего класса не будут мучаться с такими проблемами, которые мы имеем с supplier'ом.

2018-03-24 07:16 UTC, jzuken commented
конфликт с мастером

2018-04-04 09:27 UTC, merged