Hw13
subject-name-here/Java-Fall2017-202 pull request #19
Opened 2018-05-04 09:19 UTC by subject-name-here

2018-05-14 07:49 UTC, jzuken commented
конфликт с мастером

2018-05-14 08:05 UTC, jzuken requested changes

2018-05-14 08:05 UTC, jzuken commented on hw13/src/test/resources/dir1/kek1
> +the cake is a.py
для подобных тестов есть классная штука: junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html

2018-05-14 08:05 UTC, jzuken commented on hw13/src/test/java/ru/spbau/mit/java/paradov/ClientTest.java
> +        String expected = "7\n" + "f1 false\n" + "f2 false\n" + "finf false\n"
а переводы строк тоже бы нужно кроссплатформенно обрабатывать. например, так: https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator--

2018-05-14 08:05 UTC, jzuken commented on hw13/src/test/java/ru/spbau/mit/java/paradov/ClientTest.java
> +public class ClientTest {
тесты на клиент и сервер вместе это хорошо и правильно, но было бы неплохо их по отдельности ещё проверить

2018-05-14 08:05 UTC, jzuken commented on hw13/src/main/java/ru/spbau/mit/java/paradov/Client.java
> +            if (type == 1) {
хорошо бы его завернуть в enum и как-то переиспользовать между клиентом и сервером

2018-05-14 08:05 UTC, jzuken commented on hw13/src/main/java/ru/spbau/mit/java/paradov/ServerMain.java
> +            throw new NotEnoughArgumentsException("Expected at least one argument: port number.");
а смысл кидать тут исключение? кто его поймает? просто пишите в консоль текст, не издевайтесь над пользователями

2018-05-14 08:05 UTC, jzuken commented on hw13/src/main/java/ru/spbau/mit/java/paradov/Client.java
> +                saveFile(dis, path);
ну хорошо бы всё же как-то говорить пользователю о том, что файл скачался

2018-05-14 08:05 UTC, jzuken commented on hw13/src/main/java/ru/spbau/mit/java/paradov/Client.java
> +        try (DataOutputStream dos = new DataOutputStream(new FileOutputStream(new File(filename)))) {
а если попытаться скачать каталог, то он просто создаст файл размера 0 с таким именем. как-то не очень

2018-05-20 16:53 UTC, subject-name-here commented on hw13/src/main/java/ru/spbau/mit/java/paradov/Client.java
> +        try (DataOutputStream dos = new DataOutputStream(new FileOutputStream(new File(filename)))) {
Но тогда без дополнительного запроса нельзя отличить директорию от пустого (или несуществующего) файла. Что лучше:
а) создать новый вид запроса, чтобы получать информацию о конкретном файле (противоречит заданию);
б) посылать запросы list и в клиенте их парсить (ничему не противоречит, но запрашивать лист файлов, если хотим получить информацию только об одном - нехорошо);
в) не сохранять файлы с размером 0 (совсем странно, но избавляет от всех проблем быстро)?

2018-05-21 08:53 UTC, jzuken commented on hw13/src/main/java/ru/spbau/mit/java/paradov/Client.java
> +        try (DataOutputStream dos = new DataOutputStream(new FileOutputStream(new File(filename)))) {
не очень понял про "нельзя отличить директорию от пустого файла", вам API джавы не хватает для этого? как обрабатывать такие запросы с точки зрени логики приложения -- выбор ваш. можете на сервере ругаться на запросы get к директориям, а потом доносить это до пользователя. можете создавать на клиенте пустую папку, можете рекурсивно выкачивать весь каталог -- дело ваше, но надо, чтобы для пользователя это действие выглядело целостным и логичным

2018-06-14 11:11 UTC, merged